[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "Isaac Lab Kangaroo"
author = "Fabio Amadio"
author_email = "fabioamadio93@gmail.com"
maintainer = "Fabio Amadio"
description="Isaac Lab locomotion tasks for the Kangaroo robot "
repository = "https://github.com/hucebot/isaaclab_kangaroo"
keywords = ["isaaclab", "locomotion"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_mimic" = {}
"isaaclab_rl" = {}
"isaaclab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "isaaclab_kangaroo"

[isaaclab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"
